sudo: false
language: node_js
notifications:
  email: true
node_js:
  - "10"
branches:
  only:
    - master
script: yarn test
env: CODECOV_TOKEN=68c38489-4793-4bfb-8f76-ebaa324053fa
after_success:
  - codecov
