#!/bin/bash

set -e

source ./scripts/git-check.sh
source ./scripts/standard-lib.sh

exit_unless_valid_branch "master"
exit_unless_clean_git_folder
exit_unless_say_yes "This script will move next to latest. Are you sure? (Ny): " "User cancelled action"
promote_next_to_latest
