#!/bin/bash

set -e

source ./scripts/version-bump.sh
source ./scripts/git-check.sh
source ./scripts/publishing.sh

semver_type=$1
dist_tag=${2:-next}
exit_unless_valid_semver "$semver_type"
exit_unless_valid_branch "master"
exit_unless_clean_git_folder
yarn test
yarn docs && git add -A && git commit -m 'Update docs'
version_bump "$semver_type"
git push --tags && git push
publish_to_dist_tag "$dist_tag"